CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email varchar NOT NULL,
                                     login varchar NOT NULL,
                                     name varchar,
                                     birthday timestamp
);
CREATE TABLE IF NOT EXISTS connections (
                                           name varchar PRIMARY KEY,
                                           synonym varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS user_friends (
                                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                                            friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                                            connection_id varchar REFERENCES connections (name) ON DELETE RESTRICT
    );
CREATE TABLE IF NOT EXISTS ratings_mpa (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     description varchar(200),
                                     release_date timestamp,
                                     duration INTEGER,
                                     rating_mpa INTEGER REFERENCES ratings_mpa (id)
    );
CREATE TABLE IF NOT EXISTS film_likes (
                                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                                          user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS film_genres (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                                           genre_id INTEGER REFERENCES genres (id) ON DELETE RESTRICT
    );

