CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email varchar NOT NULL,
                                     login varchar NOT NULL,
                                     name varchar,
                                     birthday timestamp
);
CREATE TABLE IF NOT EXISTS user_friends (
                                            user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                                            friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                                            connection varchar,
                                            PRIMARY KEY (user_id, friend_id)

    );
CREATE TABLE IF NOT EXISTS ratings_mpa (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     description varchar(200),
                                     release_date timestamp,
                                     duration INTEGER,
                                     rating_mpa INTEGER REFERENCES ratings_mpa (id)
    );
CREATE TABLE IF NOT EXISTS film_likes (
                                          film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                                          user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                                          PRIMARY KEY (film_id, user_id)
    );
CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                                           genre_id INTEGER REFERENCES genres (id) ON DELETE RESTRICT,
                                           PRIMARY KEY (film_id, genre_id)
    );

